# Generated by Django 4.2.5 on 2023-09-26 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='Имя')),
                ('lname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('born', models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='AgeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=20, verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='Имя')),
                ('lname', models.CharField(max_length=20, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('бесплатно', 'бесплатно'), ('базовая', 'базовая'), ('супер', 'супер')], max_length=20, verbose_name='Подписка')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('rating', models.FloatField(verbose_name='Оценка')),
                ('summary', models.TextField(max_length=500, verbose_name='Описание')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('actor', models.ManyToManyField(to='catalog.actor', verbose_name='Актеры')),
                ('ager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.agerate')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.country')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.director', verbose_name='Режиссер')),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.genre')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.status')),
            ],
        ),
    ]
