# Generated by Django 4.2.5 on 2023-09-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age_years',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Возраст(лет)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.breed', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date',
            field=models.DateField(verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.diagnosis', verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.doctor', verbose_name='Доктор'),
        ),
        migrations.RemoveField(
            model_name='animal',
            name='drug',
        ),
        migrations.AlterField(
            model_name='animal',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='Кличка животного'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.owner', verbose_name='Хозяин'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название породы'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cost_rub',
            field=models.IntegerField(verbose_name='Стоимость приема'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя доктора'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=20, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Фамилия доктора'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(max_length=20, verbose_name='Доза'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название лекарства'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя хозяина'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Фамилия хозяина'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='tel',
            field=models.CharField(max_length=12, verbose_name='Телефон хозяина'),
        ),
        migrations.AddField(
            model_name='animal',
            name='drug',
            field=models.ManyToManyField(to='catalog.medicine', verbose_name='Лекарствa'),
        ),
    ]
